### ISSUE TITLE
add a framework header file 

### ISSUE THREAD

**Issue by aelam** [IFTTT/FastttCamera#24]
I use in it in swift, I have to import all the files one by one into bridge header
why not add a header such as FasttCameraKit.h which imports all public header files

**Comment by lauraskelton** [comment]
You only need to import FastttCamera/FastttCamera.h or FastttCamera/FastttFilterCamera.h into your bridging header, just like if you were importing them into your Objective-C class. The other files not included in those headers are internal to FastttCamera.
