### ISSUE TITLE
Swift implementation

### ISSUE THREAD

**Issue by joebernard** [IFTTT/FastttCamera#26]
Hi!

I'm trying to implement the camera in Swift. So far I've been able to instantiate it, take a picture, and manipulate the resulting pic.

Where I'm running into trouble is with the functions in AVCaptureDevice+FastttCamera.m. I can't seem to get the syntax right to call these functions in Swift.

```
var myCam = FastttCamera()
if FastttCamera.isFlashAvailableForCameraDevice(myCam.cameraDevice){
    myCam.setCameraFlashMode(FastttCameraFlashMode.Off)
}

```

_'FastttCamera' does not have a member named 'setCameraFlashMode'_

I know I'm probably approaching this incorrectly but figured I'd ask for help since I'm stuck. If someone could take a quick look I'd really appreciate it.

**Comment by DimaVartanian** [comment]
Have you tried setting it using normal property dot syntax? 
`myCam.cameraFlashMode = FastttCameraFlashMode.Off`

That should work.

**Comment by joebernard** [comment]
Ah, it's a property not a method. I see. Thank you!
