### ISSUE TITLE
Swift not recognizing enum FastttCameraFlashMode

### ISSUE THREAD

**Issue by ahanmal** [IFTTT/FastttCamera#27]
Hi - I'm trying to check the cameraFlashMode while using Swift 2.0. For some reason, I get the error 
`Enum case 'On' is not a member of type 'FastttCameraFlashMode?'` with the following: 

``` swift
@IBAction func switchFlash(sender: AnyObject) {
        var flashMode: FastttCameraFlashMode
        var flashTitle: String
        switch self.camera?.cameraFlashMode {
        case FastttCameraFlashMode.On:
            flashMode = FastttCameraFlashMode.Off
            flashTitle = "Flash Off"
        default:
            flashMode = FastttCameraFlashMode.On
            flashTitle = "Flash On"
        }

        if let camera = camera {
            if camera.isFlashAvailableForCurrentDevice() {
                camera.cameraFlashMode = flashMode
                flashButton.setTitle(flashTitle, forState: UIControlState.Normal)
            }
        }
    }
```

The odd thing is that I can set the `flashMode` perfectly fine, but the switch is not working. The same happens for Off and Auto. I'm not sure if this is an iOS 9 issue or a Fasttt issue. If it's an Apple issue, then I can file a Radar.

Thanks,
Ahan

**Comment by mdelmaestro** [comment]
@ahanmal The problem is that you camera is an optional property. To resolve your issue you can either force unwrap the camera 

``` swift
self.camera!.cameraFlashMode
```

or optional bind like

``` swift
if let camera = self.camera {
    switch camera.cameraFlashMode {
        ....
    }
}
```

**Comment by ahanmal** [comment]
@samurai91 Sorry, I wasn't clear on the error. The line that raises the issue is `case FastttCameraFlashMode.On:`. 

I looked at the source declaration and do not see any issues. Any ideas?

**Comment by mnmaraes** [comment]
Hmm, did you try what @samurai91 said? Because that's exactly how the error he describes manifests itself.

`FastttCameraFlashMode?` type is different than `FastttCameraFlashMode`. Try the optional bind solution and it should work.

**Comment by ahanmal** [comment]
@mnmaraes @samurai91 Ah, yes - now it works. Interesting that you have to use an optional bind for this scenario.

Thanks for everything!
