### ISSUE TITLE
Conflicting return type issue in Xcode7.0(7A220) with FastttCamera 0.3.2

### ISSUE THREAD

**Issue by ecoopnet** [IFTTT/FastttCamera#36]
After I updated to Xcode7.0 from 6.4,
I've got a build warning like below.

```
Pods/FastttCamera/FastttCamera/FastttCamera.m:164:1: Conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned long')
```

i think it is the same problem with this link:
https://forums.developer.apple.com/thread/6165

**Comment by lauraskelton** [comment]
Updated to new Xcode 7 `UIInterfaceOrientationMask` return type https://github.com/IFTTT/FastttCamera/commit/5aa7bf76aae73084edd0f23635d506302b9508cf

**Comment by ecoopnet** [comment]
it worked fine, thanks :+1:
