### ISSUE TITLE
'Expected a Type' error since Xcode 7

### ISSUE THREAD

**Issue by iain-reid** [IFTTT/FastttCamera#39]
After opening project on Xcode 7 and updating pods - I received an 'Expected a Type' error on this line:

`- (CGRect)fastttCropRectFromPreviewLayer:(AVCaptureVideoPreviewLayer *)previewLayer;`

I thought Cocoapods might be to blame so I've reverted pod to the version I was using before (0.2.9) to no effect. I've removed all pods from the project, cleaned and then re-added - but no joy. I'm at a bit of a loss!

Image below is what I see - and I can provide more detail if required. Any thoughts would be much appreciated. Thanks.

![image](https://cloud.githubusercontent.com/assets/1871804/10049527/c89222b6-620f-11e5-9dfe-c01aae0227f9.png)

**Comment by lauraskelton** [comment]
@DeepLight I'm not seeing this error. Could you make sure that the `AVFoundation` framework is being included in your pods project?

The current pod version of FastttCamera is 0.3.3 - I would try using the latest version, deleting the pods directory and podfile.lock, and running pod install again, just in case something got messed up in your project settings.

**Comment by iain-reid** [comment]
Apologies for the late response - but I did as you said and it worked! Thanks!
