### ISSUE TITLE
can this support the filters of GPUImage？

### ISSUE THREAD

**Issue by Cj370118568** [IFTTT/FastttCamera#40]

**Comment by lauraskelton** [comment]
If you're an advanced user you could access the `stillCamera` property and the `previewLayer` of the fastttfiltercamera directly, and apply whatever GPUImage effects you can build. You might wind up needing to make your own FastttCamera subclass to handle this advanced use case. 

Under the hood, the FastttCamera filters do use a GPUImageLookupFilter.
