### ISSUE TITLE
First startup of the camera , it is not possible to zoom

### ISSUE THREAD

**Issue by RSDessin** [IFTTT/FastttCamera#41]
when I was returning from the background you can use it .

Do you have a problem with the following ?
_setupCaptureSession method of FastttCamera.m
The following has not been read at the time of the first start-up .

```
            if (self.isViewLoaded && self.view.window) {
                [self startRunning];
                [self _insertPreviewLayer];
                [self _setPreviewVideoOrientation];
                [self _resetZoom];
            }
```

In Xcode7 Console
    (lldb) po [(UIView *)self.view window]
     nil

**Comment by lauraskelton** [comment]
@RSDessin I can't reproduce that issue in either of the demo apps (running iOS9 on an iPhone 6).

I'm not sure what view controller you are in when you're printing `po [(UIView *)self.view window]`, but if the view's window is `nil`, that generally means the view controller is not visible yet or hasn't been added to a superview. Make sure that you aren't removing it from its parent view controller when the application goes into the background. If you can't figure out what's going on, more details to reproduce the issue would be helpful.

**Comment by RSDessin** [comment]
Thank you for your reply.
It has been resolved by changing the timing to call the FastttCamera.
The timing of viewDidLoad,
po [(UIView *) self.view window]
It was nil.
at the timing of viewDidAppear, we were able to confirm that the value is entered.

Thank you for your help
