### ISSUE TITLE
Invalid Podfile - Unsupported Options 'exclusive=>true' with CocoaPod v1.0 

### ISSUE THREAD

**Issue by laventura** [IFTTT/FastttCamera#55]
Hi,

I'm testing out from the **Example** directory.
On running pod install, I get this error message (See attached pic)

Is this known?  (Sorry, I'm a bit new to CocoaPods)

thanks
<img width="970" alt="screen shot 2016-05-26 at 2 41 19 pm" src="https://cloud.githubusercontent.com/assets/419789/15591174/5adf15d2-2350-11e6-873f-473e7ebf76cb.png">

**Comment by maxmeyers** [comment]
Good catch - CocoaPods recently updated to version 1.0, which is incompatible with some older Podfiles. I've updated it in https://github.com/IFTTT/FastttCamera/commit/e22e0b8e398f49909b1981b462476fdfb82a481e, so if you pull master you should be all set.
