### ISSUE TITLE
Add support for Torch instead of Flash?

### ISSUE THREAD

**Issue by DimaVartanian** [IFTTT/FastttCamera#6]
This is actually not a huge change and can of course just be bolted on by a user but I figure it might be worth it to include an option to turn on the Torch before taking a picture rather than just flashing it (I do it this way in my apps because I find it lets me compose my shot better on the first try, since the picture has time to refocus nicely and you can adjust your angle to minimize glare). Any thoughts?

**Comment by lauraskelton** [comment]
Great suggestion, I'll look into adding this as an optional setting in the next version.

**Comment by lauraskelton** [comment]
Thanks to @samurai91 for adding torch mode!
